### PR TITLE
Change designprinciples headers to black main.css.scss

### PR DESCRIPTION
**Pull request by HarryTrimble**
Red headers aren't normally used. 

I've not tested the change.

### CODE REVIEW

**Comment by robinwhittleton** [comment]
There are some other uses of `$highlight-collur` including link styles. Do we want to audit and remove completely?

**Comment by HarryTrimble** [comment]
Not sure. 

How might I do that?

I just want to change the headers to black.

**Comment by HarryTrimble** [comment]
Took some code away to: 
- active links up top aren't red 
- blogpost links are blue

Add code to:

- full stop after each heading number

**Comment by robinwhittleton** [comment]
I’ve been making these changes in dev tools with Harry, here’s a screenshot of what it looked like at the end. Unfortunately my dev VM is way out of date and I can’t run it directly, but it should look this this for testing.

page-fullpage

**Comment by nickcolley** [comment]
Sat with Harry to squash the commits down over at https://github.com/alphagov/design-principles/pull/279

**Pull request closed without merging**
