### PR TITLE
Use wraith to test changes

### PR DESCRIPTION
**Pull request by jabley**
Adds wraith configuration files, excludes wraith output from git.

# Pre-requisites

You will need wraith, imagemagick, and phantomsjs or similar.

`gem install wraith`
`brew install phantomjs`
`brew install imagemagick`

# Usage

Take a baseline of the current version

`wraith history configs/config.yaml`

Switch to your feature branch and make changes.

`wraith latest configs/config.yaml`

This should generate a gallery containing diffs of the pages, at
various resolutions.

### CODE REVIEW

**Comment by dsingleton** [comment]
Just ran this locally and it works really :+1: 

I don't have strong feelings on the `wraith` config files, but it seems to do the trick.

**Comment by fofr** [comment]
What does an example diff look like?

**Comment by dsingleton** [comment]
I have some examples from https://github.com/alphagov/info-frontend/pull/48:

https://dl.dropboxusercontent.com/u/262911/info-pages/index.html

**Comment by dsingleton** [comment]
I've added added a commit to hide the cookie/survey bars, which were causing me diff problems for [another change](https://github.com/alphagov/design-principles/pull/247), but i'd be happy to merge this otherwise.

@fofr how do you feel?

**Comment by benilovj** [comment]
This looks really good :+1: 

The wraith integration looks really generic and I can imagine it being really useful for many repos – is it worth adding this in somewhere upstream (eg into `govuk_frontend_toolkit`)?

**Comment by dsingleton** [comment]
> The wraith integration looks really generic and I can imagine it being really useful for many repos – is it worth adding this in somewhere upstream (eg into govuk_frontend_toolkit)?

The not-generic bits (`paths` and `domains` in `config.yaml) are tricky to make generic, and _i think_ the config file would need to be duplicated for each repos.

Ideally we'd be able to re-use most of the config and pass in URLs/domains via command line params, but wraith doesn't seem to support that, I may have missed something though.

We'd like to use wraith for frontend migrations in the future, but in the mean time it would be nice to get this merged, so it's setup and working in at least one app.

**Pull request merged**
