### PR TITLE
Update designprinciples.html.erb

### PR DESCRIPTION
**Pull request by blangry**
Added in a "you" to make "should remember" have a subject.

### CODE REVIEW

**Comment by issyl0** [comment]
Hi @blangry! Thanks for contributing!

Just a thought: does "you should" need to be there at all though, or could it just be "remember", given we've started the sentence with "Have empathy", not "You should have empathy"?

**Comment by AndrewVos** [comment]
@issyl0 Agree, probably remove both words.

**Comment by gemmaleigh** [comment]
Looks like the agreement here was to remove "you should". Closing in favour of #274.

**Comment by issyl0** [comment]
Sorry, I never did tidy this up!

**Pull request closed without merging**
