### PR TITLE
Make design principles headers and links consistent with rest of GOV.UK

### PR DESCRIPTION
**Pull request by nickcolley**
- Updated the links to be consistent
- Updated the list to be consistent

screencapture-0-0-0-0-3023-design-principles-1481197696035

### CODE REVIEW

**Comment by nickcolley** [comment]
We need to check that this only changes this page since this repo serves not only these principles.

**Comment by quis** [comment]
Before, for posterity:

screencapture-gov-uk-design-principles-1481198036242

**Comment by markhurrell** [comment]
happy with changing the link colour in the body and the header colour, but I'd prefer if we keep the anchor links at the top as they were. they get screengrabbed a lot for presentations and i think the current version is more legible in that context

**Comment by alexmuller** [comment]
> We need to check that this only changes this page since this repo serves not only these principles.

I think it only really serves this page now*, so please delete as much as you want.

\* and https://www.gov.uk/design-principles/performanceframework

**Comment by 36degrees** [comment]
https://www.gov.uk/transformation is also served from this repo, but I'm _reasonably_ sure it's a completely different layout and set of assets.

**Comment by nickcolley** [comment]
Going to close this out for now, will review later.

**Pull request closed without merging**
